menu_admin_index:
  path: /
  defaults:
  controller: 'SymfonySimpleSite\Menu\Controller\AdminController::index'

menu_admin_new_sub_menu:
  path: /new-sub-menu/{id}
  defaults:
  controller: 'SymfonySimpleSite\Menu\Controller\AdminController::newSubMenu'

menu_admin_edit:
  path: /edit/{id}
  defaults:
  controller: 'SymfonySimpleSite\Menu\Controller\AdminController::edit'

menu_admin_new_menu:
  path: /new-menu
  controller: 'SymfonySimpleSite\Menu\Controller\AdminController::newRoot'

