menu_admin_index:
  path: /
  controller: 'MartenaSoft\Menu\Controller\AdminController::index'


menu_admin_create:
  path: /create/{parent}
  controller: 'MartenaSoft\Menu\Controller\AdminController::create'

menu_admin_edit:
  path: /edit/{id}
  controller: 'MartenaSoft\Menu\Controller\AdminController::edit'

menu_admin_delete:
  path: /config/delete/{id}
  controller: 'MartenaSoft\Menu\Controller\AdminController::delete'

menu_admin_up:
  path: /config/up/{id}
  controller: 'MartenaSoft\Menu\Controller\AdminController::up'

menu_admin_down:
  path: /config/down/{id}
  controller: 'MartenaSoft\Menu\Controller\AdminController::down'

