menu_admin_index:
  path: /
  controller: 'MartenaSoft\Menu\Controller\AdminController::index'

menu_admin_config_index:
  path: /config/{page}
  controller: 'MartenaSoft\Menu\Controller\AdminConfigController::index'
  defaults:
    page: 1
  requirements:
    page: \d+


menu_admin_config_save:
  path: /config/save/{id}
  controller: 'MartenaSoft\Menu\Controller\AdminConfigController::save'
  defaults:
    id: 0
  requirements:
    id: \d+
