menu_admin_config_index:
  path: /{page}
  controller: 'MartenaSoft\Menu\Controller\AdminConfigController::index'
  defaults:
    page: 1
  requirements:
    page: \d+

menu_admin_config_save:
  path: /save/{id}
  controller: 'MartenaSoft\Menu\Controller\AdminConfigController::save'
  defaults:
    id: 0
  requirements:
    id: \d+

menu_admin_config_delete:
  path: /delete/{id}
  controller: 'MartenaSoft\Menu\Controller\AdminConfigController::deleteConfig'
  defaults:
    id: 0
  requirements:
    id: \d+

menu_admin_config_view:
  path: /view/{id}
  controller: 'MartenaSoft\Menu\Controller\AdminConfigController::viewConfig'
  defaults:
    id: 0
  requirements:
    id: \d+
